[package]
name = "shiguredo_cmake"
version = "4.3.1"
edition = "2024"
rust-version = "1.88"
authors = ["Shiguredo Inc."]
license = "Apache-2.0"
description = "Download and cache prebuilt CMake binaries from official GitHub releases"
homepage = "https://github.com/shiguredo/cmake-rs"
repository = "https://github.com/shiguredo/cmake-rs"
readme = "README.md"
include = ["/src/**", "/build.rs", "LICENSE", "README.md"]

[[bin]]
name = "cmake"
path = "src/main.rs"

[dependencies]
cmake = "0.1"

[build-dependencies]
shiguredo_toml = "2026.1.0"

[package.metadata.external-dependencies.cmake]
version = "4.3.1"

[package.metadata.external-dependencies.cmake.sha256]
macos-universal = "c21fe4ade82a6a236aae0b9fbd8263c7ac6824a3fb32d03594456e30b06f3b7f"
linux-x86_64 = "208d76804009cbe8ec9aea0aa052c857c6e59bd289b43b9941c99324dc78b1d8"
linux-aarch64 = "2c0eca48ac7d0e3a8b4120b801d48903b0630c8ff1e73c44a90398a300dec1ac"
windows-x86_64 = "03a610be931546474e46a442d171ef10532f4fc847de9cf76b7a8065bbef6a23"
windows-arm64 = "e8aac0daf1c34f4752e9705cfe3d926a10cd42ead76d67b9cf7265c21c2cc705"
