[package]
name = "shiguredo_cmake"
version = "4.4.1"
edition = "2024"
rust-version = "1.93"
description = "Download and cache prebuilt CMake binaries from official GitHub releases"
readme = "README.md"
homepage = "https://github.com/shiguredo/cmake-rs"
repository = "https://github.com/shiguredo/cmake-rs"
license = "Apache-2.0"
include = ["/build.rs", "/src/**", "LICENSE", "README.md"]

[package.metadata.external-dependencies.cmake]
version = "4.4.1"

[package.metadata.external-dependencies.cmake.sha256]
macos-universal = "2425c063fefd6869366e77ae0ac0333233eee00eb05581bac89e204b357e939c"
linux-x86_64 = "c2e2994ee4a5573899e6a774d2c16cb878a47e97a562854bb72159b21b9347ea"
linux-aarch64 = "91442e0e97cdf2531eac4ddcaac1fdf7b20dd8ebf0bebd89bf12f82b2818071e"
windows-x86_64 = "091919e1cde162b69d2d5e0f3b1f5670c973e72133f78126fbb18042947d6f19"
windows-arm64 = "dc59d9f377f891b8da42ede22f53717034a9d093092fceaf6297feeec6afba29"

[[bin]]
name = "cmake"
path = "src/main.rs"

[dependencies]
cmake = "0.1"

[build-dependencies]
shiguredo_toml = "2026.2"
